# Generated by Django 6.0.3 on 2026-09-13 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverMemberRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this supervision relationship is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(help_text='The user acting as caregiver (must have CAREGIVER role).', on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(help_text='The user acting as member (must have PATIENT role).', on_delete=django.db.models.deletion.CASCADE, related_name='member_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caregiver-Member Relationship',
                'verbose_name_plural': 'Caregiver-Member Relationships',
                'indexes': [models.Index(fields=['caregiver', 'is_active'], name='accounts_ca_caregiv_a15d68_idx'), models.Index(fields=['member', 'is_active'], name='accounts_ca_member__8d04ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('caregiver', 'member'), name='unique_caregiver_member_relationship')],
            },
        ),
    ]
