# Generated by Django 6.0.3 on 2026-09-13 15:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cognitive Game',
                'verbose_name_plural': 'Cognitive Games',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Difficulty level from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, help_text='Accuracy percentage (0.00 to 100.00).', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_time_ms', models.PositiveIntegerField(default=0, help_text='Total gameplay time in milliseconds (cannot be negative).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('member', models.ForeignKey(help_text='The member playing the session (must have PATIENT role).', on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Positive sequential round number (1, 2, ...).', validators=[django.core.validators.MinValueValidator(1)])),
                ('stimulus_data', models.JSONField(blank=True, default=dict, help_text='Structured JSON data of stimuli presented during this round.')),
                ('expected_response', models.JSONField(blank=True, default=dict, help_text='Structured JSON data of expected correct response.')),
                ('actual_response', models.JSONField(blank=True, default=dict, help_text='Structured JSON data of actual member response.')),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Response latency in milliseconds (cannot be negative).')),
                ('mistake_count', models.PositiveIntegerField(default=0, help_text='Number of mistaken interactions before round completion.')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints requested during this round.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.gamesession')),
            ],
            options={
                'verbose_name': 'Game Round',
                'verbose_name_plural': 'Game Rounds',
                'ordering': ['session', 'round_number'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['member', 'game'], name='games_games_member__5fa0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['member', 'started_at'], name='games_games_member__3a9dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status'], name='games_games_status_e6c8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['started_at'], name='games_games_started_d0dddc_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['session', 'round_number'], name='games_gamer_session_f1dbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['is_correct'], name='games_gamer_is_corr_35ce70_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('session', 'round_number'), name='unique_round_per_session'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='check_positive_round_number'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(('response_time_ms__gte', 0)), name='check_non_negative_response_time'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(('mistake_count__gte', 0)), name='check_non_negative_mistake_count'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.CheckConstraint(condition=models.Q(('hints_used__gte', 0)), name='check_non_negative_hints_used'),
        ),
    ]
