# Generated by Django 6.0.3 on 2026-09-13 16:14

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial_games'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='hints_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of hints requested during this round.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='mistake_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of mistaken interactions before round completion.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='response_time_ms',
            field=models.PositiveIntegerField(default=0, help_text='Response latency in milliseconds (cannot be negative).', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['member'], name='games_games_member__04b6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['game'], name='games_games_game_id_66eece_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='check_difficulty_range'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='check_non_negative_score'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gte', 0)), name='check_non_negative_max_score'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('accuracy__gte', 0), ('accuracy__lte', 100)), name='check_accuracy_range'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('total_time_ms__gte', 0)), name='check_non_negative_total_time'),
        ),
    ]
