# Generated by Django 6.0.3 on 2026-09-13 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Routine title (e.g., Morning Wellness Routine).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='General notes or instructions for this routine.')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Target date for this daily routine schedule.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this routine schedule is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='The member this routine is assigned to (must have PATIENT role).', on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Routine',
                'verbose_name_plural': 'Daily Routines',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Action item (e.g., Take Morning BP Medicine, Drink Glass of Water).', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed instructions for the item.')),
                ('scheduled_time', models.TimeField(blank=True, help_text='Planned time of day for this routine item.', null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the member has marked this task as completed.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when task was marked as completed.', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Chronological sequence order within the routine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='routines.routine')),
            ],
            options={
                'verbose_name': 'Routine Item',
                'verbose_name_plural': 'Routine Items',
                'ordering': ['display_order', 'scheduled_time', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['member', 'date', 'is_active'], name='routines_ro_member__f68268_idx'),
        ),
        migrations.AddIndex(
            model_name='routineitem',
            index=models.Index(fields=['routine', 'is_completed'], name='routines_ro_routine_e36554_idx'),
        ),
        migrations.AddIndex(
            model_name='routineitem',
            index=models.Index(fields=['scheduled_time'], name='routines_ro_schedul_71a262_idx'),
        ),
    ]
