# Generated by Django 6.0.3 on 2026-09-13 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, help_text='General notes or guidance for this routine.'),
        ),
        migrations.AlterField(
            model_name='routineitem',
            name='title',
            field=models.CharField(help_text='Action item (e.g., Morning Walk, Drink Glass of Water, Water the Garden).', max_length=200),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['member', '-date'], name='routines_ro_member__2c61ea_idx'),
        ),
    ]
