# Generated by Django 6.0.3 on 2026-09-13 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or event name, preserved verbatim.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Reminiscence story, context, or notes, preserved verbatim.')),
                ('image', models.FileField(blank=True, help_text='Optional photograph file for visual reminiscence therapy.', null=True, upload_to='memories/images/')),
                ('audio_clip', models.FileField(blank=True, help_text='Optional audio voice note from family members or loved ones.', null=True, upload_to='memories/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='The member who owns this memory (must have PATIENT role).', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'created_at'], name='memories_me_member__b44429_idx')],
            },
        ),
    ]
