# Generated by Django 6.0.3 on 2026-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.FileField(blank=True, help_text='Optional photograph file for visual reminiscence and cognitive wellness.', null=True, upload_to='memories/images/'),
        ),
    ]
