# Generated by Django 6.0.3 on 2026-09-13 17:56

import apps.memories.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_memory_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the familiar person (e.g., Priya, Rajesh, Dev).', max_length=100)),
                ('relationship', models.CharField(help_text='Relationship to the patient (e.g., Daughter, Son, Wife, Husband, Grandchild, Friend).', max_length=100)),
                ('photo', models.FileField(help_text='Clear portrait photograph for facial recognition activity.', upload_to=apps.memories.models.familiar_person_photo_path, validators=[apps.memories.models.validate_image_file])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this person is included in the Familiar Faces game pool.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='The patient this familiar person is associated with (must have PATIENT role).', on_delete=django.db.models.deletion.CASCADE, related_name='familiar_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Familiar Person',
                'verbose_name_plural': 'Familiar People',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['member', 'is_active'], name='memories_fa_member__1ec0fe_idx'), models.Index(fields=['member', 'name'], name='memories_fa_member__af5642_idx')],
            },
        ),
    ]
